### PR TITLE
Documentation Improvement

### PR DESCRIPTION
**Pull request by ColeJetton**
- Extended Examples.rst to include the notebook
- Changed AST_sampling to include a link to the AST
- Added general outlines to main readme and links
- created example subfolder readme (Note, some functions omitted since they are for testing)

### CODE REVIEW

**Comment by hulsed** [comment]
I left some comments. Overall, I think we shouldn't have Examples.rst and Examples.md duplicating each other. My preference would be for you to:
- merge all your new content from examples.md into examples.rst (the nice thing about rst is it lets us automatically render the notebooks in our docs)
- move examples.rst to /examples
- update the link from the readme
- update the toctree in index.rst to link to the new location for examples.rst

**Comment by ColeJetton** [comment]
That makes sense. I’m send the update shortly.

**Comment by ColeJetton** [comment]
Updates are now included.

**Review by hulsed — COMMENTED** [review]
This is good--the one thing left to do is move the actual Examples.rst file to /examples.

**Comment by ColeJetton** [comment]
Documentation location fixed.

**Pull request merged**
